// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9bH5fIG2XeKkXSBddL0a3ngrE42uwQs0',
    appId: '1:474520707823:android:3ff0e4e55c31f4efccb11a',
    messagingSenderId: '474520707823',
    projectId: 'todos-f8011',
    storageBucket: 'todos-f8011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7u7M8cZVZWTU_xmcrrnE1-fQ1jukTzpg',
    appId: '1:474520707823:ios:daf89c28f77fbf56ccb11a',
    messagingSenderId: '474520707823',
    projectId: 'todos-f8011',
    storageBucket: 'todos-f8011.appspot.com',
    iosClientId:
        '474520707823-t03f1fmd3i6l5r3tcsjrmjlb6r5vc2sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todos',
  );
}
